name: 변경된 파일 Lint Check

on:
  pull_request_target:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    name: 🔍 변경된 파일 Lint 검사
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: ✅ 기준 브랜치 체크아웃
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      - name: 📦 pnpm 설치
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: 🛠 Node.js 설정
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: 📥 의존성 설치
        run: pnpm install

      - name: 🔄 변경된 파일 목록 추출
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          base_sha: ${{ github.event.pull_request.base.sha }}
          sha: ${{ github.event.pull_request.head.sha }}

      - name: 🔍 Lint 검사 실행
        run: |
          echo "${{ steps.changed-files.outputs.all_changed_files }}" > changed_files.txt
          grep -E '\.(js|jsx|ts|tsx)$' changed_files.txt > js_ts_files.txt || echo '' > js_ts_files.txt
          # YAML, JSON, SVG 등의 비 JS/TS 파일 제외
          grep -v -E '\.(yml|yaml|json|svg)$' js_ts_files.txt > lint_files.txt || echo '' > lint_files.txt

          if [ -s lint_files.txt ]; then
            echo "변경된 JS/TS 파일:"
            cat lint_files.txt
            cat lint_files.txt | xargs pnpm exec eslint
          else
            echo "변경된 JS/TS 파일 없음. ESLint 생략."
          fi
